In [14]:
# Empty and Full Numpy Array

import numpy as np
A = 55 * np.ones((3,4)) # Create a 3x4 full numpy array where every element is equal to 55.
A_ = np.full((3,4), fill_value=55)
B = np.empty((3,4)) # Create a 3x4 empty numpy array

In [20]:
# Convert Python Sequences to 1D ndarray
type(np.array([1,2,3]))

numpy.ndarray

In [25]:
# Convert Python Sequences to 2D ndarray
np.array([[1,2,3],[4,5,6]]).ndim

2

In [35]:
# One-byte ndarray elements
# Create a 2-dimensional array of size 3x3 named x, composed of 1-byte integer elements.
x = np.array([[1,2,3],[1,127,3]], dtype='i1')
x

array([[  1,   2,   3],
       [  1, 127,   3]], dtype=int8)

In [31]:
np.info(np.int8)
np.iinfo(np.int8)


 int8()

Signed integer type, compatible with C ``char``.
Character code: ``'b'``.
Canonical name: ``np.byte``.
Alias *on this platform*: ``np.int8``: 8-bit signed integer (-128 to 127).


Methods:

  all  --  Not implemented (virtual attribute)
  any  --  Not implemented (virtual attribute)
  argmax  --  Not implemented (virtual attribute)
  argmin  --  Not implemented (virtual attribute)
  argsort  --  Not implemented (virtual attribute)
  astype  --  Not implemented (virtual attribute)
  byteswap  --  Not implemented (virtual attribute)
  choose  --  Not implemented (virtual attribute)
  clip  --  Not implemented (virtual attribute)
  compress  --  Not implemented (virtual attribute)
  conj  --  None
  conjugate  --  Not implemented (virtual attribute)
  copy  --  Not implemented (virtual attribute)
  cumprod  --  Not implemented (virtual attribute)
  cumsum  --  Not implemented (virtual attribute)
  diagonal  --  Not implemented (virtual attribute)
  dump  --  Not implemented (virt

iinfo(min=-128, max=127, dtype=int8)

In [40]:
# Evenly Spaced Values Numpy Array
# Create an array containing the numbers 0 to 999 and store it in variable a1 .
a1 = np.array(range(1000))
a1_ = np.arange(1000)

In [46]:
# End of the interval in ndarray in a range of numbers
# Create an array of dtype float containing the numbers -3 to 3 and store it in variable a2 .
# (The number 3 itself is not in the array)
a2 = np.array(range(7), dtype='float') - 3
a2_ = np.arange(-3,3,dtype=float)

In [50]:
# Ants move in the numpy array
# Create an array that starts at 2 and goes up to 10 in steps of 0.1 and store it in variable a3
# (The number 10 itself is not in the array)
a3 = np.arange(-2,10,0.1) # third one is step
a3

array([-2.00000000e+00, -1.90000000e+00, -1.80000000e+00, -1.70000000e+00,
       -1.60000000e+00, -1.50000000e+00, -1.40000000e+00, -1.30000000e+00,
       -1.20000000e+00, -1.10000000e+00, -1.00000000e+00, -9.00000000e-01,
       -8.00000000e-01, -7.00000000e-01, -6.00000000e-01, -5.00000000e-01,
       -4.00000000e-01, -3.00000000e-01, -2.00000000e-01, -1.00000000e-01,
        1.77635684e-15,  1.00000000e-01,  2.00000000e-01,  3.00000000e-01,
        4.00000000e-01,  5.00000000e-01,  6.00000000e-01,  7.00000000e-01,
        8.00000000e-01,  9.00000000e-01,  1.00000000e+00,  1.10000000e+00,
        1.20000000e+00,  1.30000000e+00,  1.40000000e+00,  1.50000000e+00,
        1.60000000e+00,  1.70000000e+00,  1.80000000e+00,  1.90000000e+00,
        2.00000000e+00,  2.10000000e+00,  2.20000000e+00,  2.30000000e+00,
        2.40000000e+00,  2.50000000e+00,  2.60000000e+00,  2.70000000e+00,
        2.80000000e+00,  2.90000000e+00,  3.00000000e+00,  3.10000000e+00,
        3.20000000e+00,  

In [52]:
# Precision loss is closer to us than you think.
# Create an array that starts at -0.5 and goes up to 0.2 in steps of 0.1 and store it in variable a4.
# (The number 0.2 itself is not in the array)
a4 = np.arange(-0.5, 0.2, 0.1)
a4

array([-5.00000000e-01, -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
       -1.00000000e-01, -1.11022302e-16,  1.00000000e-01])

In [55]:
# Uniformly Spaced Numbers
# Create an array containing 7 elements between the numbers 1 to 121 
# in such a way that the numbers 1 and 121 are part of this array and
# the distance between the numbers should be equal. store the array in a5 variable
a5 = np.linspace(1,121,7)

In [56]:
a5

array([  1.,  21.,  41.,  61.,  81., 101., 121.])

In [57]:
# End Inclusive Array
# Create an array containing 16 elements between the numbers -3 to 3 
# in such a way that the numbers -3 and 3 are part of this array 
# and the distance between the numbers should be equal. store the array in a6 variable
a6 = np.linspace(-3,3,16)

In [58]:
a6

array([-3. , -2.6, -2.2, -1.8, -1.4, -1. , -0.6, -0.2,  0.2,  0.6,  1. ,
        1.4,  1.8,  2.2,  2.6,  3. ])

In [65]:
# Diagonal 2-D array
# Create an 4×4 array that its main diameter is equal to 1 and other elements are equal to zero 
# and store this variable in a7 variable
a7 = np.eye(4,4)

In [62]:
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
# Upper Diagonal Matrix
# Create an 5×5 array that its second diameter above the main diameter 
# is equal to 1 and other elements are equal to zero and store this variable in a8 variable
a8 = np.eye(5,5,2)
a8

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
# Diagonal 2D Array
# Create a 7×7 array that it's main diameter contains the numbers 
# from 1 to 121 with equal distance and other elements are equal to zero 
# then store it in the a9 variable.
a9 = np.diag(np.linspace(1,121,7))
a9

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  21.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  41.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  61.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  81.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 101.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 121.]])

In [96]:
# Diagonal Array Indexing
# A 5×5 array is stored in a variable named z, store the value of the 
# second diameter lower than the main diameter in a variable called a10

z = np.arange(25).reshape(5,5)
mask = np.eye(5,5,-2,dtype=bool)
a10 = z[mask]
a10_ = np.diag(z, -2)

In [100]:
# Fill your array with zeros
# Create a 6x4 array with all zero elements and store it in variable a11
a11 = np.zeros((6,4))
a11

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
# Fill your array with ones
# Create a 6x4 array with all one elements and store it in variable a12
a12 = np.ones((6,4))
a12

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
# Random Array
# Create a 6x4 array with all random elements and store it in variable a13 .
a13 = np.random.random((6,4))
a13

array([[0.58340769, 0.0441891 , 0.22117999, 0.41045977],
       [0.62088725, 0.6858718 , 0.1507721 , 0.03418021],
       [0.13391878, 0.01739325, 0.4889931 , 0.45428922],
       [0.51979699, 0.24374395, 0.2414989 , 0.35415175],
       [0.19634476, 0.83225038, 0.64485177, 0.8162738 ],
       [0.1255898 , 0.44740372, 0.4657158 , 0.32001295]])

In [125]:
# New array without initializing entries
# Create a 6x4 array with empty elements and store it in variable a14 .
a14 = np.empty(shape=(6,4))
a14

array([[0.58340769, 0.0441891 , 0.22117999, 0.41045977],
       [0.62088725, 0.6858718 , 0.1507721 , 0.03418021],
       [0.13391878, 0.01739325, 0.4889931 , 0.45428922],
       [0.51979699, 0.24374395, 0.2414989 , 0.35415175],
       [0.19634476, 0.83225038, 0.64485177, 0.8162738 ],
       [0.1255898 , 0.44740372, 0.4657158 , 0.32001295]])

In [132]:
# Array filled with value
# Create a 8x3 array with all its elements equal to the "Pytopia"  and then store it in the a15  variable.
a15 = np.full((8,3), fill_value='Pytopia')
a15

array([['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia']], dtype='<U7')

In [134]:
# An array with repeating rows
# Using numpy with one line of code, create an array similar to the one below
#  and store it in the a16  variable.
a16 = np.full((6,3),[-np.inf,np.nan,np.inf])
a16

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])

In [135]:
# numpy.ndarray object
# Store the type of object a in variable a_type
a = np.array([1, 2, 3])
a_type = type(a)
a_type

numpy.ndarray

In [139]:
# Array scalar types
# Store the type of object a[0] in variable a0_type

a = np.array([1, 2, 3])
a[0]
a0_type = type(a[0])

In [142]:
# Data-type object
# Store the data type of object a in variable a_data_type

a = np.array([1, 2, 3])
a_data_type = a.dtype
a_data_type

In [148]:
# An array with 4-byte elements
# Create a 2-dimensional array of size 3 x 4 named x, composed of 4-byte integer elements:
x = np.random.randint(1,10,size=(3,4), dtype="i4")
x

array([[9, 9, 6, 8],
       [3, 1, 9, 4],
       [8, 9, 6, 6]], dtype=int32)

In [153]:
# Find Numpy Non-Zero Mean
# Find the average of non-zero elements of 
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])

a[a != 0].mean()

4.625

In [159]:
# Numpy Array Middle Rows
# Code where indicated by #? to access the middle rows of a_3d:

a_3d = np.array(
    [[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
    [[50, 65, 8], [70, 85, 10], [11, 22, 33]]]
)
print(a_3d)
a_3d[:,1]


[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]


array([[30, 45, 55],
       [70, 85, 10]])